# Generated by Django 3.2.5 on 2021-08-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offTheRecords', '0002_auto_20210802_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Manger'), (2, 'Artist'), (3, 'Contractor')], default=2),
        ),
    ]
