# Generated by Django 3.2.5 on 2021-08-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offTheRecords', '0004_auto_20210802_0450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='linkedIn',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='tikTok',
            new_name='tiktok',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='youTube',
            new_name='youtube',
        ),
        migrations.RemoveField(
            model_name='facebook',
            name='password',
        ),
        migrations.RemoveField(
            model_name='soundcloud',
            name='password',
        ),
        migrations.RemoveField(
            model_name='spotifyforartists',
            name='password',
        ),
        migrations.RemoveField(
            model_name='twitter',
            name='password',
        ),
        migrations.RemoveField(
            model_name='youtube',
            name='password',
        ),
        migrations.AddField(
            model_name='artist',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bandcamp',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebook',
            name='friends',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebook',
            name='verified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='soundcloud',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='soundcloud',
            name='streams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spotifyforartists',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spotifyforartists',
            name='monthly_listeners',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twitter',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twitter',
            name='verified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='youtube',
            name='subscribers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artist',
            name='ascap',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bmi',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='cashapp',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='googleDrive',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='mlc',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='payPal',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='songTrust',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='soundExchange',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='venmo',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='verified',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='linkedin',
            name='connections',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ASCAP',
        ),
        migrations.DeleteModel(
            name='BMI',
        ),
        migrations.DeleteModel(
            name='Cashapp',
        ),
        migrations.DeleteModel(
            name='GoogleDrive',
        ),
        migrations.DeleteModel(
            name='MLC',
        ),
        migrations.DeleteModel(
            name='PayPal',
        ),
        migrations.DeleteModel(
            name='SongTrust',
        ),
        migrations.DeleteModel(
            name='SoundExchange',
        ),
        migrations.DeleteModel(
            name='Venmo',
        ),
    ]
