# Generated by Django 3.2.5 on 2021-08-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offTheRecords', '0006_alter_artist_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
