# Generated by Django 3.2.5 on 2021-08-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offTheRecords', '0009_alter_artist_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiktok',
            name='password',
        ),
        migrations.AddField(
            model_name='tiktok',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tiktok',
            name='verified',
            field=models.IntegerField(default=0),
        ),
    ]
