# Generated by Django 3.2.5 on 2021-08-03 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offTheRecords', '0011_contractor_info_specialty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebook',
            old_name='friends',
            new_name='followers',
        ),
        migrations.RenameField(
            model_name='linkedin',
            old_name='connections',
            new_name='followers',
        ),
        migrations.RenameField(
            model_name='youtube',
            old_name='subscribers',
            new_name='followers',
        ),
    ]
