# Generated by Django 3.2.5 on 2021-08-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offTheRecords', '0013_alter_artist_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tiktok',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
