# Generated by Django 3.2.5 on 2021-08-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offTheRecords', '0014_auto_20210803_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyforartists',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
