# Generated by Django 3.2.5 on 2021-08-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offTheRecords', '0019_auto_20210804_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='song_per_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='num_od',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='num_songs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
