# Generated by Django 3.2.5 on 2021-08-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offTheRecords', '0020_auto_20210804_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='num_od',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='num_songs',
            field=models.IntegerField(default=1),
        ),
    ]
