# Generated by Django 3.2.5 on 2021-08-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offTheRecords', '0021_auto_20210804_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='song_per_duration',
            field=models.IntegerField(default=1),
        ),
    ]
