# Generated by Django 3.2.5 on 2021-08-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offTheRecords', '0022_alter_item_song_per_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='started_on',
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
