# Generated by Django 3.2.5 on 2021-08-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offTheRecords', '0023_auto_20210805_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.IntegerField(choices=[(0, 'In The Box'), (1, 'Studio')], default=1),
        ),
    ]
