# Generated by Django 3.2.5 on 2021-08-05 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offTheRecords', '0024_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offTheRecords.project'),
        ),
    ]
